import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class SolverTest {
    String INPUT = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............""";

    @Test
    void solveFirst() {
        var result = Solver.debugFirst(Field.fromString(INPUT));
        assertThat(result).isEqualTo(21);
    }

    @Test
    void solveSecond() {
        var result = Solver.debugSecond(Field2.fromString(INPUT));
        assertThat(result).isEqualTo(40);
    }
}
